export const PRIMARY_PAGE_FAMILIES = [
  "home",
  "academics",
  "grades",
  "finances",
  "personal",
  "resources",
] as const;

export type PrimaryPageFamily = (typeof PRIMARY_PAGE_FAMILIES)[number];
export type PageFamily = PrimaryPageFamily | "albert";

export interface PageFamilyDefinition {
  description: string;
  keywords: readonly string[];
  label: string;
  navigationHint: string;
  nativeLabels: readonly string[];
}

export const PAGE_FAMILY_DEFINITIONS: Record<
  PageFamily,
  PageFamilyDefinition
> = {
  albert: {
    label: "Albert",
    description: "Your official NYU student services workspace",
    keywords: [],
    navigationHint: "Official student services workspace",
    nativeLabels: [],
  },
  home: {
    label: "Home",
    description:
      "Your starting point for classes, first-week help, and time-sensitive tasks",
    keywords: [
      "class schedule",
      "classes taking",
      "classes today",
      "check holds",
      "class catalog",
      "course registration",
      "class registration",
      "course catalog",
      "course catalogue",
      "browse course catalog",
      "browse course offerings",
      "browse available courses for the upcoming term",
      "browse available classes",
      "add and validate your classes to your shopping cart",
      "enroll in classes for the next term at your designated registration day and time",
      "course search",
      "current classes",
      "enroll in class",
      "check your registration date and time",
      "make sure you don't have any registration holds that will block you from registering",
      "enrollment date",
      "find a class",
      "find a course",
      "register for classes",
      "when can i register",
      "registration time",
      "enrollment appointment",
      "enrollment dates",
      "search classes",
      "search course catalog",
      "see deadlines",
      "to do list",
      "timetable",
      "when are my classes",
      "show classes",
    ],
    navigationHint: "Find classes, check holds, and review your schedule",
    nativeLabels: ["Home"],
  },
  academics: {
    label: "Academics",
    description: "Course planning, advising, enrollment, and degree progress",
    keywords: [
      "add classes",
      "academic advisor",
      "your academic advisor",
      "find your advisor",
      "what can my advisor help with",
      "learn more about academic advisors",
      "learn more about academic advisor",
      "academic planning",
      "academic planning and support",
      "academic resource center",
      "accelerated studies",
      "adjusting to the college environment",
      "choosing a major minor double major or double minor",
      "apply for graduation",
      "apply to graduate",
      "advisor help",
      "advisor appointment",
      "academic advisor appointment",
      "schedule advisor",
      "schedule advisor appointment",
      "schedule an advisor meeting",
      "choosing a major",
      "choose a major",
      "contact advisor",
      "course selection and sequencing",
      "course planning",
      "change major",
      "change program",
      "declare major",
      "degree audit",
      "audit my degree",
      "degree progress tracking",
      "defining educational and career goals",
      "developing skills and time management",
      "developing skills, time management, and other techniques for academic success",
      "drop a class",
      "drop class",
      "drop courses",
      "dropping or adding courses",
      "adjust your schedule during the add/drop period",
      "having trouble registering",
      "get help with registration",
      "register at another nyu school",
      "applying for a minor",
      "registering after de-enrollment",
      "requesting a leave of absence or term/total withdrawal",
      "waitlists, swap, and edit swap",
      "how and when to apply for graduation",
      "meet with your advisor to discuss your class schedule and review your degree requirements",
      "find advisor",
      "finding your advisor",
      "combined joint degree accelerated and other specialized programs",
      "liaison linkage with academic departments",
      "major planning",
      "majors, minors and academic planning",
      "meet advisor",
      "nyu academic advising framework",
      "plan degree",
      "preparing for graduation",
      "prepare for your meeting",
      "professional edge",
      "improve skills with professional edge",
      "explore academic opportunities",
      "visit the academic resource center",
      "degree progress report",
      "expected graduation",
      "graduation date",
      "graduation application",
      "when do i graduate",
      "plan courses",
      "plan my courses",
      "securing tutorial and other academic support",
      "switch major",
      "swap a class",
      "swap class",
      "tracking and maintaining progress",
      "tracking and maintaining progress within the college core curriculum and toward degree requirements",
      "track your degree progress",
      "stay on track for graduation",
      "tracking degree progress",
      "unique academic opportunities",
      "understanding school and university policies and procedures",
      "undergraduate advisement",
      "who is advisor",
      "your academic advisor",
      "withdraw from a class",
      "withdraw from courses",
      "class withdrawal",
      "course withdrawal",
      "what classes need",
    ],
    navigationHint:
      "Plan courses, manage enrollment, meet your advisor, and track degree progress",
    nativeLabels: ["Academics"],
  },
  grades: {
    label: "Grades & Transcripts",
    description: "View grades, get transcripts, and prove enrollment",
    keywords: [
      "check grades",
      "check your grades",
      "enrollment letter",
      "enrollment verification letter",
      "enrollment proof",
      "myhub enrollment",
      "national student clearinghouse",
      "official transcript",
      "request official and unofficial transcripts",
      "request official enrollment and degree verification",
      "student records and transcripts",
      "get transcript",
      "request your transcript",
      "enrollment and degree verification",
      "graduation",
      "graduation requirements",
      "prove enrolled",
      "proof enrollment",
      "proof of enrollment",
      "report card",
      "see grades",
      "share enrollment",
      "unofficial transcript",
      "verify enrollment",
      "verify your enrollment or degree",
      "access authentication services like apostilles",
      "authentication and apostilles",
      "how to receive your diploma",
      "certify your eligibility for ny state tap",
      "new york state tuition assistance program tap",
      "new york state tuition assistance program",
      "view grades",
      "transfer credit",
    ],
    navigationHint: "View grades, get transcripts, and prove enrollment",
    nativeLabels: ["Grades & Transcripts"],
  },
  finances: {
    label: "Finances",
    description: "Check balances, pay tuition, view bills, and manage financial aid",
    keywords: [
      "amount due",
      "accept aid",
      "accept my aid",
      "accept financial aid",
      "accept or decline awards",
      "bills payments and refunds",
      "tuition and fee rates",
      "tuition and student charges",
      "how billing and payment work at nyu",
      "when and how to pay",
      "payment due dates",
      "accessing your bill",
      "accessing your students bill",
      "ways to pay",
      "refund methods",
      "financial aid refunds",
      "when to expect a refund",
      "housing payments and tax documents",
      "check your bursar and financial aid accounts",
      "contact the bursar team",
      "uaw students",
      "bursar",
      "check balance",
      "decline aid",
      "decline financial aid",
      "financial aid package",
      "how much owe",
      "how much is tuition",
      "financial aid status",
      "manage your personal finances",
      "need help financial aid",
      "pay bill",
      "pay a bill",
      "pay my bill",
      "payment plan",
      "pay tuition",
      "pay tuition bill",
      "review charges",
      "review awards",
      "see tuition bill",
      "student account",
      "tuition due",
      "tuition and fees",
      "tuition cost",
      "view tuition bill",
      "what owe",
    ],
    navigationHint:
      "Check balances, pay tuition, view bills, and manage financial aid",
    nativeLabels: ["Finances"],
  },
  personal: {
    label: "Personal Info",
    description: "Review official details and update contact information",
    keywords: [
      "change address",
      "change email",
      "change legal name",
      "change name",
      "change phone",
      "date of birth",
      "edit profile",
      "emergency contact",
      "gender",
      "legal name",
      "preferred name",
      "new address",
      "home address",
      "new email address",
      "new emergency contact",
      "new phone number",
      "name pronunciation",
      "nationality",
      "personal information",
      "update your personal information",
      "update your student records",
      "updating your student records",
      "managing guest users",
      "manage guest users",
      "pronouns",
      "mobile phone",
      "update contact info",
      "make sure your contact information is up-to-date in albert",
      "update address",
      "update email",
      "update emergency contact",
      "update name",
      "update phone",
    ],
    navigationHint:
      "Review official personal details or update contact information",
    nativeLabels: ["Personal Info"],
  },
  resources: {
    label: "Other Resources",
    description: "NYU services, calendars, offices, and support",
    keywords: [
      "campus events",
      "events",
      "campus bookstore",
      "campus map",
      "campus wifi",
      "campus wi fi",
      "campus police",
      "campus resources",
      "accessibility and accommodations",
      "athletics and fitness",
      "academic support",
      "gyms and campus recreation",
      "sustainability",
      "student centers and spaces",
      "student tech centers",
      "student life",
      "book appointment",
      "schedule appointment",
      "tech wifi",
      "technology help",
      "academic and campus resources",
      "academic services",
      "academic tutoring at nyu",
      "from questions to confidence",
      "explore the tutoring centers",
      "tutoring at nyu",
      "bobst library",
      "academic tutoring",
      "external student complaint procedures",
      "find more student guides",
      "ferpa privacy rights",
      "ferpa privacy rights and how to grant consent to disclose information",
      "ferpa rights",
      "learn about your ferpa rights",
      "how to request your official transcript",
      "request official transcript",
      "request your official transcript",
      "financial education",
      "financial aid appointment",
      "scholarship",
      "scholarships",
      "financial aid and registration",
      "help with your bill financial aid registration and more",
      "answers about your bill financial aid registration international student services and more",
      "student government",
      "service opportunities and civic engagement",
      "safety security and transportation",
      "wifi streaming and technology",
      "intramural and club sports",
      "multicultural education and programs",
      "veteran services",
      "center for global spiritual life",
      "kaplan all access",
      "nyu kaplan all access free kaplan test prep courses for nyu students",
      "review course offerings and register for kaplan test prep courses",
      "mlk jr scholars",
      "mlk jr scholars program",
      "career development",
      "undergraduate students",
      "clubs and organizations",
      "student clubs",
      "find clubs and other student organizations on campus",
      "explore hundreds of ways to get involved",
      "communities and groups",
      "connect with other students",
      "commuter students",
      "commuter and off campus students",
      "counseling",
      "counseling appointment",
      "campus accessibility",
      "disability support",
      "disability services",
      "disability accommodations",
      "testing accommodations",
      "accessibility",
      "advice for your first semester",
      "advice for transfer students",
      "time management guide",
      "feeling unsafe",
      "first year student",
      "graduate students",
      "get help",
      "how do i get started",
      "need help with nyu",
      "get involved",
      "getting involved",
      "health and wellness",
      "mental health appointment",
      "first year orientation",
      "first semester",
      "first semester advice",
      "getting around campus",
      "get support",
      "get support from a student success specialist",
      "a student success specialist",
      "learn more about student success specialists",
      "what do i do first",
      "what should i do first",
      "where do i start",
      "get inspired",
      "watch a video",
      "keep it kind",
      "wellbeing across nyu",
      "resources and support for students",
      "resources for campus partners",
      "leave of absence support",
      "support for students on a leave of absence",
      "support for students on a loa",
      "glossary of nyu and higher education terms",
      "year 2 at nyu",
      "midterm feedback",
      "text messages",
      "success toolbox",
      "student services",
      "student support",
      "meet with an expert to guide you through nyu student services",
      "check this page for links to virtual programming resources and support services across campus",
      "programs to inspire success",
      "opportunity programs",
      "surveys for success",
      "about the office",
      "about student success",
      "meet our team",
      "our initiatives",
      "center for student success insights",
      "cssi",
      "how we engage",
      "trainings and workshops",
      "how we engage modules",
      "module 1 introduction to how we engage",
      "non discrimination and anti harassment policy training",
      "constructive dialogue institute",
      "perspectives program",
      "inclusive dialogue institute",
      "around the longest table",
      "fall 2026 how we engage toolkit faqs",
      "interfaith supper club",
      "listening labs",
      "multifaith advisory council",
      "nyu in dialogue",
      "the resilient society",
      "violet voices",
      "inclusive dialogue video series",
      "inclusive dialogue and leadership video series",
      "programs and events",
      "berkley institute for civil discourse",
      "berkley institute for civil discourse and civic solutions",
      "centers for connection and community",
      "community standards",
      "ndah policy training",
      "university student conduct policy",
      "guidance and expectations on student conduct",
      "additional support resources",
      "housing and dining",
      "food accessibility assistance",
      "leadership for students",
      "leadership opportunities",
      "fraternities and sororities",
      "lgbtq students",
      "military students and vets",
      "military students and veterans",
      "students in the military and veterans",
      "program board",
      "student media",
      "volunteer service",
      "volunteering",
      "class activities boards",
      "spiritual life advisor",
      "access clinical care",
      "get 24/7 support",
      "schedule appointments with doctors counselors nurses and other experts",
      "connect with us for urgent mental health needs or medical questions or support after sexual assault",
      "student health center",
      "wellbeing initiatives",
      "explore tips and strategies for everyday healthy living",
      "get expert guidance on bringing wellbeing into your clubs classrooms lounges and more",
      "student wellbeing team",
      "free flu shots",
      "group fitness",
      "green grant",
      "accessibility specialist",
      "public transportation discounts",
      "report an incident",
      "online programming services and opportunities",
      "global services",
      "health wellness accessibility services",
      "leadership and awards",
      "on demand media activities",
      "religious and spiritual life",
      "residential life opportunities",
      "social justice and diversity opportunities",
      "student communities and organizations",
      "sustainability opportunities",
      "volunteering and relief opportunities",
      "class registration transcripts graduation",
      "registering for classes",
      "student records and transcripts",
      "final exams and course feedback",
      "graduation and diplomas",
      "graduation checklist",
      "applying to graduate",
      "commencement",
      "apostilles",
      "apostille document authentication",
      "resources for military-connected students",
      "resources for military connected students",
      "va education benefits",
      "post 9/11 gi bill and yellow ribbon program",
      "montgomery gi bill",
      "benefits for spouses and dependents",
      "certify your va benefits",
      "additional important dates and deadlines",
      "other public services",
      "student conduct and community standards",
      "register to vote",
      "voting info for students",
      "global awards advising",
      "academic and career opportunities",
      "authoring your nyu story",
      "stamps scholars at nyu",
      "anbryce scholars",
      "banking in nyc",
      "winter break guide",
      "book an appointment with nyu connect",
      "make a one on one appointment and find tips for remote learning",
      "find tips for remote learning",
      "centralized online platform",
      "centralized online platform that provides a holistic approach to ensuring student success across the university",
      "individualized guidance",
      "technological resources",
      "academic coaching individualized guidance technological resources",
      "more about studentlink",
      "learn more about studentlink",
      "help with you bill financial aid registration and more",
      "student visa and immigration",
      "student visa immigration",
      "nyu bookstores",
      "campus cash and nyu card",
      "resources for student success",
      "writing center",
      "university learning centers",
      "student complaint information",
      "new york resident student complaint information",
      "student grievance procedures for certain distance education students sara",
      "additional resources for sara complaints",
      "regional accreditation complaint process",
      "contact information for non sara member state residents",
      "contact information by state",
      "speaking freely",
      "key links",
      "libraries",
      "maps",
      "new student",
      "new student orientation",
      "newly admitted student",
      "nyu engage find clubs organizations and events",
      "orientation",
      "parking",
      "printing",
      "printing on campus",
      "bookstore",
      "shuttle",
      "school id",
      "student id",
      "student id card",
      "student guides",
      "student link",
      "studentlink",
      "studentlink center",
      "student support",
      "student activities board",
      "learn more about getting involved",
      "learn more about student activities board",
      "learn more about campus resources",
      "student services",
      "students with disabilities",
      "students with children",
      "students of color",
      "spiritual life",
      "transfer students",
      "resources for students",
      "planning for study abroad",
      "solving personal problems that impede academic work",
      "student information and resources",
      "student tech guide",
      "tech checklist for new students",
      "new student registration guide",
      "general bidding registration guide",
      "activate your netid",
      "activate your net id",
      "manage guest users in albert",
      "updating your student records",
      "managing guest users",
      "studying away",
      "involvement in co-curricular educational opportunities and activities",
      "support appointment",
      "time management",
      "technology help",
      "transit",
      "transportation",
      "transfer student",
      "welcome week",
      "wellbeing",
      "wellbeing resources",
      "wi fi",
      "wifi",
      "eduroam",
    ],
    navigationHint: "NYU services, offices, and support",
    nativeLabels: ["Other Resources", "OTHER RESOURCES"],
  },
};
