export const PRIMARY_PAGE_FAMILIES = [
  "home",
  "academics",
  "grades",
  "finances",
  "personal",
  "resources",
] as const;

export type PrimaryPageFamily = (typeof PRIMARY_PAGE_FAMILIES)[number];
export type PageFamily = PrimaryPageFamily | "albert";

export interface PageFamilyDefinition {
  description: string;
  keywords: readonly string[];
  label: string;
  navigationHint: string;
  nativeLabels: readonly string[];
}

export const PAGE_FAMILY_DEFINITIONS: Record<
  PageFamily,
  PageFamilyDefinition
> = {
  albert: {
    label: "Albert",
    description: "Your official NYU student services workspace",
    keywords: [],
    navigationHint: "Official student services workspace",
    nativeLabels: [],
  },
  home: {
    label: "Home",
    description:
      "Your starting point for classes, first-week help, and time-sensitive tasks",
    keywords: [
      "class schedule",
      "classes taking",
      "classes today",
      "check holds",
      "class catalog",
      "course registration",
      "class registration",
      "course catalog",
      "course catalogue",
      "browse course catalog",
      "browse course offerings",
      "course search",
      "current classes",
      "enroll in class",
      "enrollment date",
      "find a class",
      "find a course",
      "register for classes",
      "when can i register",
      "registration time",
      "enrollment appointment",
      "enrollment dates",
      "search classes",
      "search course catalog",
      "see deadlines",
      "to do list",
      "timetable",
      "when are my classes",
      "show classes",
    ],
    navigationHint: "Find classes, check holds, and review your schedule",
    nativeLabels: ["Home"],
  },
  academics: {
    label: "Academics",
    description: "Course planning, advising, enrollment, and degree progress",
    keywords: [
      "add classes",
      "academic advisor",
      "academic planning",
      "academic planning and support",
      "academic resource center",
      "accelerated studies",
      "adjusting to the college environment",
      "apply for graduation",
      "apply to graduate",
      "advisor help",
      "advisor appointment",
      "academic advisor appointment",
      "schedule advisor",
      "schedule advisor appointment",
      "schedule an advisor meeting",
      "choosing a major",
      "choose a major",
      "contact advisor",
      "course selection and sequencing",
      "course planning",
      "change major",
      "change program",
      "declare major",
      "degree audit",
      "audit my degree",
      "degree progress tracking",
      "defining educational and career goals",
      "developing skills and time management",
      "developing skills, time management, and other techniques for academic success",
      "drop a class",
      "drop class",
      "find advisor",
      "finding your advisor",
      "combined joint degree accelerated and other specialized programs",
      "liaison linkage with academic departments",
      "major planning",
      "majors, minors and academic planning",
      "meet advisor",
      "nyu academic advising framework",
      "plan degree",
      "preparing for graduation",
      "prepare for your meeting",
      "professional edge",
      "expected graduation",
      "graduation date",
      "graduation application",
      "when do i graduate",
      "plan courses",
      "plan my courses",
      "securing tutorial and other academic support",
      "switch major",
      "swap a class",
      "swap class",
      "tracking and maintaining progress",
      "unique academic opportunities",
      "understanding school and university policies and procedures",
      "undergraduate advisement",
      "who is advisor",
      "your academic advisor",
      "withdraw from a class",
      "what classes need",
    ],
    navigationHint:
      "Plan courses, manage enrollment, meet your advisor, and track degree progress",
    nativeLabels: ["Academics"],
  },
  grades: {
    label: "Grades & Transcripts",
    description: "View grades, get transcripts, and prove enrollment",
    keywords: [
      "check grades",
      "enrollment letter",
      "enrollment verification letter",
      "enrollment proof",
      "myhub enrollment",
      "national student clearinghouse",
      "official transcript",
      "get transcript",
      "graduation",
      "graduation requirements",
      "prove enrolled",
      "proof enrollment",
      "proof of enrollment",
      "report card",
      "see grades",
      "share enrollment",
      "unofficial transcript",
      "verify enrollment",
      "view grades",
      "transfer credit",
    ],
    navigationHint: "View grades, get transcripts, and prove enrollment",
    nativeLabels: ["Grades & Transcripts"],
  },
  finances: {
    label: "Finances",
    description: "Check balances, pay tuition, view bills, and manage financial aid",
    keywords: [
      "amount due",
      "accept aid",
      "accept my aid",
      "accept financial aid",
      "accept or decline awards",
      "bills payments and refunds",
      "bursar",
      "check balance",
      "decline aid",
      "decline financial aid",
      "financial aid package",
      "how much owe",
      "how much is tuition",
      "financial aid status",
      "manage your personal finances",
      "need help financial aid",
      "pay bill",
      "pay a bill",
      "pay my bill",
      "payment plan",
      "pay tuition",
      "pay tuition bill",
      "review charges",
      "review awards",
      "see tuition bill",
      "student account",
      "tuition due",
      "tuition and fees",
      "tuition cost",
      "view tuition bill",
      "what owe",
    ],
    navigationHint:
      "Check balances, pay tuition, view bills, and manage financial aid",
    nativeLabels: ["Finances"],
  },
  personal: {
    label: "Personal Info",
    description: "Review official details and update contact information",
    keywords: [
      "change address",
      "change email",
      "change legal name",
      "change name",
      "change phone",
      "date of birth",
      "edit profile",
      "emergency contact",
      "gender",
      "legal name",
      "preferred name",
      "new address",
      "home address",
      "new email address",
      "new emergency contact",
      "new phone number",
      "name pronunciation",
      "nationality",
      "personal information",
      "pronouns",
      "mobile phone",
      "update contact info",
      "update address",
      "update email",
      "update emergency contact",
      "update name",
      "update phone",
    ],
    navigationHint:
      "Review official personal details or update contact information",
    nativeLabels: ["Personal Info"],
  },
  resources: {
    label: "Other Resources",
    description: "NYU services, calendars, offices, and support",
    keywords: [
      "campus events",
      "events",
      "campus bookstore",
      "campus map",
      "campus wifi",
      "campus wi fi",
      "campus police",
      "campus resources",
      "accessibility and accommodations",
      "athletics and fitness",
      "academic support",
      "gyms and campus recreation",
      "sustainability",
      "student centers and spaces",
      "student tech centers",
      "student life",
      "book appointment",
      "schedule appointment",
      "tech wifi",
      "technology help",
      "academic and campus resources",
      "academic services",
      "academic tutoring at nyu",
      "bobst library",
      "academic tutoring",
      "external student complaint procedures",
      "find more student guides",
      "financial education",
      "financial aid appointment",
      "scholarship",
      "scholarships",
      "financial aid and registration",
      "help with your bill financial aid registration and more",
      "answers about your bill financial aid registration international student services and more",
      "student government",
      "service opportunities and civic engagement",
      "safety security and transportation",
      "wifi streaming and technology",
      "intramural and club sports",
      "multicultural education and programs",
      "veteran services",
      "center for global spiritual life",
      "kaplan all access",
      "mlk jr scholars",
      "mlk jr scholars program",
      "career development",
      "clubs and organizations",
      "student clubs",
      "communities and groups",
      "commuter students",
      "commuter and off campus students",
      "counseling",
      "counseling appointment",
      "campus accessibility",
      "disability support",
      "disability services",
      "disability accommodations",
      "testing accommodations",
      "accessibility",
      "advice for your first semester",
      "advice for transfer students",
      "time management guide",
      "feeling unsafe",
      "first year student",
      "graduate students",
      "get help",
      "how do i get started",
      "need help with nyu",
      "get involved",
      "getting involved",
      "health and wellness",
      "mental health appointment",
      "first year orientation",
      "first semester",
      "first semester advice",
      "getting around campus",
      "get support",
      "get support from a student success specialist",
      "what do i do first",
      "what should i do first",
      "where do i start",
      "get inspired",
      "watch a video",
      "keep it kind",
      "wellbeing across nyu",
      "resources and support for students",
      "student services",
      "student support",
      "programs to inspire success",
      "opportunity programs",
      "surveys for success",
      "about the office",
      "about student success",
      "meet our team",
      "our initiatives",
      "center for student success insights",
      "cssi",
      "how we engage",
      "trainings and workshops",
      "how we engage modules",
      "module 1 introduction to how we engage",
      "non discrimination and anti harassment policy training",
      "constructive dialogue institute",
      "perspectives program",
      "inclusive dialogue institute",
      "inclusive dialogue video series",
      "inclusive dialogue and leadership video series",
      "programs and events",
      "berkley institute for civil discourse",
      "berkley institute for civil discourse and civic solutions",
      "centers for connection and community",
      "community standards",
      "ndah policy training",
      "university student conduct policy",
      "guidance and expectations on student conduct",
      "additional support resources",
      "housing and dining",
      "food accessibility assistance",
      "leadership for students",
      "leadership opportunities",
      "fraternities and sororities",
      "lgbtq students",
      "military students and vets",
      "military students and veterans",
      "program board",
      "student media",
      "volunteer service",
      "volunteering",
      "class activities boards",
      "spiritual life advisor",
      "access clinical care",
      "get 24/7 support",
      "student health center",
      "wellbeing initiatives",
      "group fitness",
      "green grant",
      "accessibility specialist",
      "public transportation discounts",
      "report an incident",
      "online programming services and opportunities",
      "class registration transcripts graduation",
      "other public services",
      "student conduct and community standards",
      "register to vote",
      "voting info for students",
      "global awards advising",
      "academic and career opportunities",
      "authoring your nyu story",
      "stamps scholars at nyu",
      "anbryce scholars",
      "banking in nyc",
      "winter break guide",
      "book an appointment with nyu connect",
      "make a one on one appointment and find tips for remote learning",
      "find tips for remote learning",
      "centralized online platform",
      "centralized online platform that provides a holistic approach to ensuring student success across the university",
      "individualized guidance",
      "technological resources",
      "academic coaching individualized guidance technological resources",
      "more about studentlink",
      "student visa and immigration",
      "student visa immigration",
      "nyu bookstores",
      "campus cash and nyu card",
      "resources for student success",
      "writing center",
      "university learning centers",
      "student complaint information",
      "speaking freely",
      "key links",
      "libraries",
      "maps",
      "new student",
      "new student orientation",
      "newly admitted student",
      "nyu engage find clubs organizations and events",
      "orientation",
      "parking",
      "printing",
      "printing on campus",
      "bookstore",
      "shuttle",
      "school id",
      "student id",
      "student id card",
      "student guides",
      "student link",
      "studentlink",
      "studentlink center",
      "student support",
      "student activities board",
      "student services",
      "students with disabilities",
      "students with children",
      "students of color",
      "spiritual life",
      "transfer students",
      "resources for students",
      "planning for study abroad",
      "solving personal problems that impede academic work",
      "student information and resources",
      "student tech guide",
      "studying away",
      "involvement in co-curricular educational opportunities and activities",
      "support appointment",
      "time management",
      "technology help",
      "transit",
      "transportation",
      "transfer student",
      "welcome week",
      "wellbeing",
      "wellbeing resources",
      "wi fi",
      "wifi",
      "eduroam",
    ],
    navigationHint: "NYU services, offices, and support",
    nativeLabels: ["Other Resources", "OTHER RESOURCES"],
  },
};
