export const PRIMARY_PAGE_FAMILIES = [
  "home",
  "academics",
  "grades",
  "finances",
  "personal",
  "resources",
] as const;

export type PrimaryPageFamily = (typeof PRIMARY_PAGE_FAMILIES)[number];
export type PageFamily = PrimaryPageFamily | "albert";

export interface PageFamilyDefinition {
  description: string;
  keywords: readonly string[];
  label: string;
  navigationHint: string;
  nativeLabels: readonly string[];
}

export const PAGE_FAMILY_DEFINITIONS: Record<
  PageFamily,
  PageFamilyDefinition
> = {
  albert: {
    label: "Albert",
    description: "Your official NYU student services workspace",
    keywords: [],
    navigationHint: "Official student services workspace",
    nativeLabels: [],
  },
  home: {
    label: "Home",
    description:
      "Your starting point for classes, first-week help, and time-sensitive tasks",
    keywords: [
      "class schedule",
      "check holds",
      "class catalog",
      "course registration",
      "course catalog",
      "course catalogue",
      "browse course catalog",
      "browse course offerings",
      "course search",
      "enroll in class",
      "enrollment date",
      "find a class",
      "find a course",
      "register for classes",
      "search classes",
      "search course catalog",
      "see deadlines",
      "to do list",
    ],
    navigationHint: "Find classes, check holds, and review your schedule",
    nativeLabels: ["Home"],
  },
  academics: {
    label: "Academics",
    description: "Course planning, advising, enrollment, and degree progress",
    keywords: [
      "add classes",
      "advisor help",
      "contact advisor",
      "drop a class",
      "drop class",
      "find advisor",
      "meet advisor",
      "plan degree",
      "swap a class",
      "swap class",
      "who is advisor",
      "withdraw from a class",
      "what classes need",
    ],
    navigationHint:
      "Plan courses, manage enrollment, meet your advisor, and track degree progress",
    nativeLabels: ["Academics"],
  },
  grades: {
    label: "Grades & Transcripts",
    description: "Grades, transcripts, and enrollment verification",
    keywords: [
      "check grades",
      "enrollment letter",
      "get transcript",
      "prove enrolled",
      "see grades",
      "view grades",
      "transfer credit",
    ],
    navigationHint: "View grades, get transcripts, and prove enrollment",
    nativeLabels: ["Grades & Transcripts"],
  },
  finances: {
    label: "Finances",
    description: "Tuition balances, bills, statements, and financial aid",
    keywords: [
      "amount due",
      "bills payments and refunds",
      "check balance",
      "how much owe",
      "manage your personal finances",
      "need help financial aid",
      "pay bill",
      "payment plan",
      "pay tuition",
      "review charges",
      "see tuition bill",
      "student account",
      "tuition due",
      "tuition and fees",
      "view tuition bill",
      "what owe",
    ],
    navigationHint:
      "Check balances, pay tuition, view bills, and manage financial aid",
    nativeLabels: ["Finances"],
  },
  personal: {
    label: "Personal Info",
    description: "Review official details and update contact information",
    keywords: [
      "change address",
      "change email",
      "change legal name",
      "change name",
      "change phone",
      "date of birth",
      "emergency contact",
      "gender",
      "legal name",
      "preferred name",
      "new address",
      "new email address",
      "new emergency contact",
      "new phone number",
      "update contact info",
      "update address",
      "update email",
      "update emergency contact",
      "update name",
      "update phone",
    ],
    navigationHint:
      "Review official personal details or update contact information",
    nativeLabels: ["Personal Info"],
  },
  resources: {
    label: "Other Resources",
    description: "NYU services, calendars, offices, and support",
    keywords: [
      "campus events",
      "campus bookstore",
      "campus map",
      "campus police",
      "campus resources",
      "academic and campus resources",
      "academic services",
      "communities and groups",
      "counseling",
      "disability services",
      "accessibility",
      "feeling unsafe",
      "first year student",
      "get help",
      "getting involved",
      "first year orientation",
      "first semester",
      "first semester advice",
      "getting around campus",
      "get support",
      "how we engage",
      "housing and dining",
      "key links",
      "libraries",
      "maps",
      "new student",
      "new student orientation",
      "newly admitted student",
      "orientation",
      "parking",
      "printing",
      "bookstore",
      "shuttle",
      "school id",
      "student id",
      "student id card",
      "student guides",
      "student link",
      "studentlink",
      "student support",
      "student services",
      "resources for students",
      "student information and resources",
      "student tech guide",
      "support appointment",
      "time management",
      "technology help",
      "transit",
      "transportation",
      "transfer student",
      "welcome week",
      "wellbeing",
      "wellbeing resources",
      "wi fi",
      "wifi",
    ],
    navigationHint: "NYU services, offices, and support",
    nativeLabels: ["Other Resources", "OTHER RESOURCES"],
  },
};
